export * from "./listActions"

export const CONSTANTS = {
    ADD_MEAL_ITEM: "ADD_MEAL_ITEM",
    DELETE_MEAL_ITEM: "DELETE_MEAL_ITEM",
    EDIT_MEAL_TITLE: "EDIT_MEAL_TITLE",
    EDIT_MEAL_DESCRIPTION: "EDIT_MEAL_DESCRIPTION",
    EDIT_MEAL_INGREDIENTS: "EDIT_MEAL_INGREDIENTS",
    EDIT_MEAL_INSTRUCTIONS: "EDIT_MEAL_INSTRUCTIONS",
    SELECT_RECIPE_MEAL: "SELECT_RECIPE_MEAL"
};

